
name: 1-periodic-test-bm

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/periodic-broken-link-checks.yml
  schedule:
    - cron: '3 3 * * 3'

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Pages
      #   id: pages
      #   uses: actions/configure-pages@v3
      - name: Check broken links
        env:
          INPUT_URL: https://www.bluemovement.com/de-de/
          EXCLUDE: |
            microsoft.com
            a.storyblok.com
            _next
            popages.com
            youtube
            facebook
            instagram
            [object
         # INPUT_CMD_PARAMS: "--one-page-only --verbose --buffer-size=8192 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
        run: |
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash

