name: periodic-test-bm

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/periodic-broken-link-checks.yml
  schedule:
    - cron: '3 3 * * 3'

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v1
        with:
          url: https://www.bluemovement.com/de-de/sitemap.xml
          cmd_params: '--follow-sitemap-xml --verbose --buffer-size=8192 --max-connections=10 --header="User-Agent:curl/7.54.0" --timeout=20'
